#!/bin/bash

# Manual Cloudflare Pages deployment script
# Run this AFTER completing Cloudflare signup and getting an API token

echo "=========================================="
echo "Cloudflare Pages Manual Deployment"
echo "=========================================="
echo ""
echo "STEP 1: Complete Cloudflare Setup"
echo "1. Go to: https://dash.cloudflare.com/sign-up"
echo "2. Sign up with: raven@supr.ae / rszzonxFFA21!"
echo "3. Verify email"
echo "4. Go to: https://dash.cloudflare.com/profile/api-tokens"
echo "5. Create token with 'Cloudflare Pages' template"
echo "6. Copy the token"
echo ""
echo "STEP 2: Set API Token"
echo "export CLOUDFLARE_API_TOKEN=your-token-here"
echo ""
echo "STEP 3: Deploy"
echo "cd ~/dev/talos-admin"
echo "npx wrangler pages deploy . --project-name talos-admin"
echo ""
echo "=========================================="
echo "ALTERNATIVE: GitHub Integration (FASTER!)"
echo "=========================================="
echo "1. Go to: https://dash.cloudflare.com/pages"
echo "2. Click 'Create a project' → 'Connect to Git'"
echo "3. Select 'talos-admin' repository"
echo "4. Use default settings (no build)"
echo "5. Deploy!"
echo ""
echo "Result URL: https://talos-admin.pages.dev"
echo "=========================================="
